# Generated by Django 5.1.4 on 2025-02-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='color',
            field=models.IntegerField(choices=[(0, 'Red'), (1, 'Green'), (2, 'Blue'), (3, 'Yellow'), (4, 'Purple'), (5, 'Orange'), (6, 'Pink'), (7, 'Gray')], default=0),
        ),
    ]
