# Generated by Django 5.1.4 on 2025-02-12 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0003_alter_habit_id_checkin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkin',
            options={'ordering': ['-checked_in_on']},
        ),
        migrations.AlterModelOptions(
            name='habit',
            options={'ordering': ['-created_on']},
        ),
    ]
