# Generated by Django 5.1.4 on 2025-02-19 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0004_alter_checkin_options_alter_habit_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.IntegerField(choices=[(0, 'clap'), (1, 'like'), (2, 'heart'), (3, 'trophy')])),
                ('is_seen', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL)),
                ('to_habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='habit_tracker.habit')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
